### ISSUE TITLE
Failed to fetch 66717625/shard_1.json. Retrying immediately NoSuchKey: The specified key does not exist.

### ISSUE THREAD

**Issue by boatnoodle** [near/indexers-docs#14]
After syncing on localhost for a while it throw error 
`Failed to fetch 66717625/shard_1.json. Retrying immediately NoSuchKey: The specified key does not exist.`

I followed by this tutorial `https://near-indexers.io/tutorials/lake/nft-indexer` 

How can I fix it ? Thanks you for your support.

**Comment by khorolets** [comment]
Hey! I see you've closed the issue already. 

I'll answer for the future:

While you follow the tip of the network sometimes the `near-lake-framework` tries to fetch the shards data a bit earlier than it's stored on S3. You can see messages like "Failed to fetch ... Retrying immediately" in such cases. That's totally normal though a bit noisy in the logs. In one of the next attempts, the indexer would be able to read the required file.
