### ISSUE TITLE
Migrate Indexer Docs to near-indexers.io

### ISSUE THREAD

**Issue by gagdiez** [near/indexers-docs#17]
Hi Team!

The "in-depth" indexer docs are being removed from docs.near.org since indexers now have their own website (near-indexers.io). Particularly, in the first release of our [new docs](https://near-docs.io/tools/welcome) we will only have a link pointing to your website, and no technical documentation on how to run an indexer or use near lake.

Because of this, it is important that somebody checks that all Indexer related docs from docs.near.org are correctly migrated to near-indexers.io. If something is missing, we are in danger of loosing it once we merge near-docs.io into docs.near.org.

If you need any help from us, please do let us know, and we can assist with the migration once we finish with some priority tasks.

Thanks!

P.S. We do still some docs about how to use "NEAR Indexer for Explorer", and in the future, we hope we can collaborate on adding introductory docs about near lake.

**Comment by bucanero** [comment]
We have migrated the indexer documentation back to `docs.near.org`, so I think this issue can be closed.
